ARG CUDA="10.2"
ARG CUDNN="7"

FROM nvidia/cuda:${CUDA}-cudnn${CUDNN}-devel-ubuntu18.04
MAINTAINER LiYuRui liyuruijx@pku.edu.cn

LABEL Discription="Develop environment of cuda 10.2 cudnn 7 ubuntu 18.04" version="1.0"

ARG USERNAME=ubuntu
ARG USER_UID=1000
ARG USER_GID=$USER_UID

RUN apt-get update && apt-get install -y ca-certificates
COPY ubuntu/sources.list /etc/apt
RUN groupadd --gid $USER_GID $USERNAME \
  && useradd -s /bin/bash --uid $USER_UID --gid $USER_GID -m $USERNAME \
  && apt-get update && apt-get install -y sudo \
  && echo $USERNAME ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/$USERNAME \
  && chmod 0440 /etc/sudoers.d/$USERNAME

ENV DEBIAN_FRONTEND=noninteractive
RUN ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
RUN echo 'Asia/Shanghai' >/etc/timezone

RUN sudo apt-get install -y git vim zsh curl tmux wget gcc make zlib1g-dev build-essential libbz2-dev \
  libssl-dev libreadline-dev libsqlite3-dev tk-dev \
  libpng-dev libfreetype6-dev libffi-dev openssh-server \
  locales busybox software-properties-common 

RUN export LANGUAGE=en_US.UTF-8 && \
  export LANG=en_US.UTF-8 && \
  export LC_ALL=en_US.UTF-8 && \
  sudo locale-gen en_US.UTF-8

COPY zsh/bullet-train.zsh-theme /tmp
COPY tmux/.tmux.conf /tmp 
COPY tmux/.tmux.conf.local /tmp 
COPY zsh/.zshrc /tmp
COPY oh-my-zsh/oh-my-zsh_install.sh /tmp
COPY oh-my-zsh/oh-my-zsh_plugins_install.sh /tmp
COPY pip/pip.conf /tmp
COPY pyenv/pyenv_install.sh /tmp
COPY dev_pkg/ /tmp

USER $USERNAME
WORKDIR /home/$USERNAME

RUN sudo chown -R ubuntu:ubuntu /tmp

# Install oh-my-zsh
RUN sudo usermod -s /bin/zsh ubuntu
RUN /tmp/oh-my-zsh_install.sh 
RUN /tmp/oh-my-zsh_plugins_install.sh

RUN cp /tmp/.tmux.conf ~/ && cp /tmp/.tmux.conf.local ~/ && cp /tmp/.zshrc ~/ && cp /tmp/pip.conf ~/.pip \
  && cp /tmp/bullet-train.zsh-theme ~/.oh-my-zsh/themes
RUN mkdir -p ~/.config && git clone https://github.com/tmux-plugins/tmux-resurrect ~/.config/tmux-resurrect

# Install pyenv and python 3.8.5
RUN /tmp/pyenv_install.sh && echo "\nexport PATH=\"\$HOME/.pyenv/bin:\$PATH\"\neval \"\$(pyenv init -)\"\neval \"\$(pyenv virtualenv-init -)\"" >> ~/.zshrc \
  && v=3.8.5;wget http://npm.taobao.org/mirrors/python/$v/Python-$v.tar.xz -P ~/.pyenv/cache/ \
  && CONFIGURE_OPTS=--enable-shared ~/.pyenv/bin/pyenv install $v && ~/.pyenv/bin/pyenv global $v

RUN cp -r /tmp/dev_pkg ~/

RUN rm -rf /tmp/*

EXPOSE 22 8886 8887 8888
 

